---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fallback-ui
  namespace: fallback-ui
  labels:
    app: fallback-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fallback-ui
  template:
    metadata:
      labels:
        app: fallback-ui
    spec:
      containers:
      - name: nginx
        image: nginx:1.27-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: site
          mountPath: /usr/share/nginx/html
      volumes:
      - name: site
        configMap:
          name: fallback-ui-html
          items:
          - key: index.html
            path: index.html
---
apiVersion: v1
kind: Service
metadata:
  name: fallback-ui
  namespace: fallback-ui
spec:
  type: ClusterIP
  selector:
    app: fallback-ui
  ports:
  - name: http
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fallback-ui
  namespace: fallback-ui
  annotations:
    cert-manager.io/cluster-issuer: "quick-kind-ca"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fallback-ui
            port:
              number: 80
